# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eye-chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eye-chat
pod 'WebRTC-lib'

  target 'eye-chatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eye-chatUITests' do
    # Pods for testing
  end

end
