version: "3"
services:
  server:
    build:
      context: ./eye-chat-server
      dockerfile: Dockerfile
    image: node:lts-alpine
    container_name: eye-chat-server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./eye-chat-server:/home/node/app
      - ./eye-chat-server/node_modules:/home/node/app/node_modules
    command: yarn dev

volumes:
  pgdata:
  node_modules: